tasks:
  - init: yarn install && cd server && yarn install && npx prisma generate && yarn build
ports: 
  - port: 3000
    visibility: public
    onOpen: open-browser
  - port: 4000
    visibility: public